//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stalker2Control.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stalker2Control.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на �+}1�9泓���%e*�Hx��I+x�m�MKA@���f�,^�U&lt;,ǏC��a        ///��I�߻[Z�4ᑗyۘz��q-%rg,��HV��m��1G�i���!.0���K�o�DUY|7����Z��Vm�6���D�&apos;%=I�pW��[���W����iɸ&lt;��ۜƳ�Mz|C�~���1/�\��s����:�`�8�}+gt.��%j!../../../Stalker2/Config/UserEngine.ini�+}1�9泓���%e*�Hx��I+�oZ~�c&gt;�&apos;��/�ML��uև��.
        /// </summary>
        internal static string pakchunk10000_UETools__Windows_p_pak {
            get {
                return ResourceManager.GetString("pakchunk10000(UETools)-Windows_p.pak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оlxa�v�P�5�}M�����_Y�h�h)��h)�h&apos;�A0Aӏ�A!$��.~�Sg?�����/���7��R�Y�f����t��ϓr�&gt;��K�t���\�_�7��� �
        ///h�lԥN��.G���FlG���4Z��ъ?�)sJ`�-R.�]XX�1E������b�2G�Ԕ��B&lt;$D�h:R��諓��j�-�Y^S��fB����        ///��V�z7        ///��(9M�A
        ///�J��S}/pi��i�pچ�MH%&apos;�S�H��H�F1�î@&apos; ���*K����
        ///��U��v-���tFGu�4&gt;�#�,G���!:��jd����Y�&amp;�#�DN��UZF�V4���q��vեLyD���V�~�-�	RU�rݓ��So�:�9k��4Mf��p�lF�����Os�X�������ƅG|RWWWQ �bߎ��2��L%s�F_���&quot;�R��-K7uCiᎀ�u����� [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string pakchunk10000_UETools__Windows_pak {
            get {
                return ResourceManager.GetString("pakchunk10000(UETools)-Windows.pak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на �&quot;��RRr���d��i&amp;���ޑ�c��-5�[7u/�$�Y̀m���&amp;!�����B��/�VScV�b?=&amp;MaterialInterfaceDescription_9_449F7F7B49A0151DBCAA518747C86F70MaterialInterfaceReference_8_9705C80D49B80B628B457FBD3C9C16CANoneObjectPropertyTextPropertyS_EngineMaterial/Game/UETools/Structs/S_EngineMaterial�~}��O��S
        ///��H&quot;	|��άQmD3[�d������������S
        ///��H��������mD3[�dGh�[�.3X$�9�oM�_[�� [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string pakchunk10000_UETools__Windows_ucas {
            get {
                return ResourceManager.GetString("pakchunk10000(UETools)-Windows.ucas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -==--==--==--==-�&quot;+ i8�Sn�qG	����������l�%�B��&gt;Iǚ�g��L��ݯ�A��N�W�C�;���@������P�6A\��]��Rm�d���f�����0�u��A��Ƙ;��=���+�v�R��I�^�s        ///��������F�9��_rxU�Y��6#&lt;�y�J�
        ///
        ///ޠ�qK��ͺ�����
        ///A�meD��        ///�%�}3`r&apos;�q�Oe��G��dzJ�IU��k�8�Sn�qG���H�r�&apos;�8w��P�=��������6i\Z� [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string pakchunk10000_UETools__Windows_utoc {
            get {
                return ResourceManager.GetString("pakchunk10000(UETools)-Windows.utoc", resourceCulture);
            }
        }
    }
}
